# Form implementation generated from reading ui file '.\10.5.sample_calculater_ui.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(407, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_first_num = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_first_num.setFont(font)
        self.label_first_num.setObjectName("label_first_num")
        self.horizontalLayout.addWidget(self.label_first_num)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lineEdit_first_num = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_first_num.setFont(font)
        self.lineEdit_first_num.setObjectName("lineEdit_first_num")
        self.horizontalLayout.addWidget(self.lineEdit_first_num)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_second_num = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_second_num.setFont(font)
        self.label_second_num.setObjectName("label_second_num")
        self.horizontalLayout_2.addWidget(self.label_second_num)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lineEdit_second_num = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_second_num.setFont(font)
        self.lineEdit_second_num.setObjectName("lineEdit_second_num")
        self.horizontalLayout_2.addWidget(self.lineEdit_second_num)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.pushButton_mul = QtWidgets.QPushButton(Form)
        self.pushButton_mul.setObjectName("pushButton_mul")
        self.pushButton_mul.clicked.connect(self.mull_btn_fun)
        self.horizontalLayout_3.addWidget(self.pushButton_mul)

        self.pushButton_add = QtWidgets.QPushButton(Form)
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_add.clicked.connect(self.add_btn_fun)
        self.horizontalLayout_3.addWidget(self.pushButton_add)

        self.pushButton_minus = QtWidgets.QPushButton(Form)
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.pushButton_minus.clicked.connect(self.minus_btn_fun)
        self.horizontalLayout_3.addWidget(self.pushButton_minus)

        self.pushButton_dvide = QtWidgets.QPushButton(Form)
        self.pushButton_dvide.setObjectName("pushButton_dvide")
        self.pushButton_dvide.clicked.connect(self.divied_btn_fun)
        self.horizontalLayout_3.addWidget(self.pushButton_dvide)

        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel\n"
"{\n"
"color : green\n"
"}")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def add_btn_fun(self):
        first_num = int(self.lineEdit_first_num.text())
        second_num = int(self.lineEdit_second_num.text())
        result = first_num + second_num
        self.label.setText(f"Sum : {result}")

    def minus_btn_fun(self):
        first_num = int(self.lineEdit_first_num.text())
        second_num = int(self.lineEdit_second_num.text())
        result = first_num - second_num
        self.label.setText(f"Minus : {result}")

    def mull_btn_fun(self):
        first_num = int(self.lineEdit_first_num.text())
        second_num = int(self.lineEdit_second_num.text())
        result = first_num * second_num
        self.label.setText(f"Multiplication : {result}")

    def divied_btn_fun(self):
        first_num = int(self.lineEdit_first_num.text())
        second_num = int(self.lineEdit_second_num.text())
        result = first_num / second_num
        self.label.setText(f"Divide : {result}")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_first_num.setText(_translate("Form", "First Num :"))
        self.lineEdit_first_num.setPlaceholderText(_translate("Form", "Enter first num"))
        self.label_second_num.setText(_translate("Form", "Second Num :"))
        self.lineEdit_second_num.setPlaceholderText(_translate("Form", "Enter second num"))
        self.pushButton_mul.setText(_translate("Form", "*"))
        self.pushButton_add.setText(_translate("Form", "+"))
        self.pushButton_minus.setText(_translate("Form", "-"))
        self.pushButton_dvide.setText(_translate("Form", "/"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
