# Form implementation generated from reading ui file '.\calculater_dseigen_ui.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(430, 447)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lcdNumber = QtWidgets.QLCDNumber(Form)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout.addWidget(self.lcdNumber)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.sum_btn = QtWidgets.QPushButton(Form)
        self.sum_btn.setObjectName("sum_btn")
        self.horizontalLayout_5.addWidget(self.sum_btn)
        self.mul_btn = QtWidgets.QPushButton(Form)
        self.mul_btn.setObjectName("mul_btn")
        self.horizontalLayout_5.addWidget(self.mul_btn)
        self.minus = QtWidgets.QPushButton(Form)
        self.minus.setObjectName("minus")
        self.horizontalLayout_5.addWidget(self.minus)
        self.division_btn = QtWidgets.QPushButton(Form)
        self.division_btn.setObjectName("division_btn")
        self.horizontalLayout_5.addWidget(self.division_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.num1 = QtWidgets.QPushButton(Form)
        self.num1.setObjectName("num1")
        self.horizontalLayout.addWidget(self.num1)
        self.num2 = QtWidgets.QPushButton(Form)
        self.num2.setObjectName("num2")
        self.horizontalLayout.addWidget(self.num2)
        self.num3 = QtWidgets.QPushButton(Form)
        self.num3.setObjectName("num3")
        self.horizontalLayout.addWidget(self.num3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.num4 = QtWidgets.QPushButton(Form)
        self.num4.setObjectName("num4")
        self.horizontalLayout_2.addWidget(self.num4)
        self.num5 = QtWidgets.QPushButton(Form)
        self.num5.setObjectName("num5")
        self.horizontalLayout_2.addWidget(self.num5)
        self.num6 = QtWidgets.QPushButton(Form)
        self.num6.setObjectName("num6")
        self.horizontalLayout_2.addWidget(self.num6)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.num7 = QtWidgets.QPushButton(Form)
        self.num7.setObjectName("num7")
        self.horizontalLayout_3.addWidget(self.num7)
        self.num8 = QtWidgets.QPushButton(Form)
        self.num8.setObjectName("num8")
        self.horizontalLayout_3.addWidget(self.num8)
        self.num9 = QtWidgets.QPushButton(Form)
        self.num9.setObjectName("num9")
        self.horizontalLayout_3.addWidget(self.num9)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.clear_btn = QtWidgets.QPushButton(Form)
        self.clear_btn.setObjectName("clear_btn")
        self.horizontalLayout_4.addWidget(self.clear_btn)
        self.num0 = QtWidgets.QPushButton(Form)
        self.num0.setObjectName("num0")
        self.horizontalLayout_4.addWidget(self.num0)
        self.equals = QtWidgets.QPushButton(Form)
        self.equals.setObjectName("equals")
        self.horizontalLayout_4.addWidget(self.equals)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def num1_btn_func(self):
        mytext = self.lcdNumber.get

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.sum_btn.setText(_translate("Form", "+"))
        self.mul_btn.setText(_translate("Form", "*"))
        self.minus.setText(_translate("Form", "-"))
        self.division_btn.setText(_translate("Form", "/"))
        self.num1.setText(_translate("Form", "1"))
        self.num2.setText(_translate("Form", "2"))
        self.num3.setText(_translate("Form", "3"))
        self.num4.setText(_translate("Form", "4"))
        self.num5.setText(_translate("Form", "5"))
        self.num6.setText(_translate("Form", "6"))
        self.num7.setText(_translate("Form", "7"))
        self.num8.setText(_translate("Form", "8"))
        self.num9.setText(_translate("Form", "9"))
        self.clear_btn.setText(_translate("Form", "Clear"))
        self.num0.setText(_translate("Form", "0"))
        self.equals.setText(_translate("Form", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
