# Form implementation generated from reading ui file '.\Radios_Demo.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QDialog


class Ui_Dialog(QDialog):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(624, 568)
        Dialog.setStyleSheet("QDialog{\n"
"border-color: rgb(255, 255, 127);\n"
"background-color: rgb(85, 255, 127);\n"
"}\n"
"QLabel\n"
"{\n"
"    \n"
"    color: rgb(0, 0, 255);\n"
"}")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 10, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 260, 371, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 500, 550, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto Slab SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(90, 80, 114, 143))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_python = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(14)
        self.radioButton_python.setFont(font)
        self.radioButton_python.setObjectName("radioButton_python")
        self.verticalLayout.addWidget(self.radioButton_python)
        self.radioButton_java = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(14)
        self.radioButton_java.setFont(font)
        self.radioButton_java.setObjectName("radioButton_java")
        self.verticalLayout.addWidget(self.radioButton_java)
        self.radioButton_js = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(14)
        self.radioButton_js.setFont(font)
        self.radioButton_js.setObjectName("radioButton_js")
        self.verticalLayout.addWidget(self.radioButton_js)
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(90, 330, 176, 143))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_deb = QtWidgets.QRadioButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_deb.setFont(font)
        self.radioButton_deb.setObjectName("radioButton_deb")
        self.verticalLayout_2.addWidget(self.radioButton_deb)
        self.radioButton_payball = QtWidgets.QRadioButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_payball.setFont(font)
        self.radioButton_payball.setObjectName("radioButton_payball")
        self.verticalLayout_2.addWidget(self.radioButton_payball)
        self.radioButton_deb_2 = QtWidgets.QRadioButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Oswald")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton_deb_2.setFont(font)
        self.radioButton_deb_2.setObjectName("radioButton_deb_2")
        self.verticalLayout_2.addWidget(self.radioButton_deb_2)

        self.radioButton_python.toggled.connect(self.radio_selected)
        self.radioButton_java.toggled.connect(self.radio_selected)
        self.radioButton_js.toggled.connect(self.radio_selected)
        self.radioButton_deb.toggled.connect(self.radio_selected)
        self.radioButton_payball.toggled.connect(self.radio_selected)
        self.radioButton_deb_2.toggled.connect(self.radio_selected)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def radio_selected(self):
        selected_1 = ""
        selected_2 = ""
        if self.radioButton_python.isChecked() == True:
            selected_1 = "Python"
        elif self.radioButton_java.isChecked() == True:
            selected_1 = "Java"
        elif self.radioButton_js.isChecked() == True:
            selected_1 = "JavaScript"
        if self.radioButton_deb.isChecked() == True:
                selected_2 = "Debit/Credit Card"
        if self.radioButton_payball.isChecked() == True:
                selected_2 = "Payball"
        if self.radioButton_deb_2.isChecked() == True:
                selected_2 = "Cash"
        self.label_3.setText(f"Your Book is : {selected_1},  payment is : {selected_2}")


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Choose your book :"))
        self.label_2.setText(_translate("Dialog", "select your method payment :"))
        self.radioButton_python.setText(_translate("Dialog", "Python"))
        self.radioButton_java.setText(_translate("Dialog", "Java"))
        self.radioButton_js.setText(_translate("Dialog", "JavaScript"))
        self.radioButton_deb.setText(_translate("Dialog", "Debit/Credit Card"))
        self.radioButton_payball.setText(_translate("Dialog", "Payball"))
        self.radioButton_deb_2.setText(_translate("Dialog", "Cash"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
