# Form implementation generated from reading ui file '.\CheckDemo.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QDialog


class Ui_Dialog(QDialog):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setStyleSheet("background-color: rgb(255, 228, 17);")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Caveat")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Caveat")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_pizza = QtWidgets.QCheckBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Caveat")
        font.setPointSize(18)
        self.checkBox_pizza.setFont(font)
        self.checkBox_pizza.setObjectName("checkBox_pizza")
        self.checkBox_pizza.stateChanged.connect(self.checkbox_selected)
        self.verticalLayout.addWidget(self.checkBox_pizza)
        self.checkBox_salad = QtWidgets.QCheckBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Caveat")
        font.setPointSize(18)
        self.checkBox_salad.setFont(font)
        self.checkBox_salad.setObjectName("checkBox_salad")
        self.checkBox_salad.stateChanged.connect(self.checkbox_selected)
        self.verticalLayout.addWidget(self.checkBox_salad)
        self.checkBox_salad_2 = QtWidgets.QCheckBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Caveat")
        font.setPointSize(18)
        self.checkBox_salad_2.setFont(font)
        self.checkBox_salad_2.setObjectName("checkBox_salad_2")
        self.checkBox_salad_2.stateChanged.connect(self.checkbox_selected)
        self.verticalLayout.addWidget(self.checkBox_salad_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label_result = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Caveat")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_result.setFont(font)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.verticalLayout_2.addWidget(self.label_result)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def checkbox_selected(self):
        price = 10
        if self.checkBox_pizza.isChecked():
            price += 3
        if self.checkBox_salad.isChecked():
            price += 4
        if self.checkBox_salad_2.isChecked():
            price += 5
        self.label_result.setText(f"Total price is {price}")

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "CheckDemo"))
        self.label.setText(_translate("Dialog", "Regular tuna price : $10"))
        self.label_2.setText(_translate("Dialog", "Select More :"))
        self.checkBox_pizza.setText(_translate("Dialog", "Pizza : $3"))
        self.checkBox_salad.setText(_translate("Dialog", "Salad : $4"))
        self.checkBox_salad_2.setText(_translate("Dialog", "Sausage : $5"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
