# Form implementation generated from reading ui file '.\QSpinBoxes_Example.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(818, 289)
        Form.setStyleSheet("QWidget\n"
"{\n"
"background-color :rgb(255, 255, 127)\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Caveat")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_pen_price = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Caveat")
        font.setPointSize(16)
        self.lineEdit_pen_price.setFont(font)
        self.lineEdit_pen_price.setObjectName("lineEdit_pen_price")
        self.horizontalLayout.addWidget(self.lineEdit_pen_price)
        self.spinBox = QtWidgets.QSpinBox(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.spinBox.setFont(font)
        self.spinBox.setObjectName("spinBox")
        self.spinBox.valueChanged.connect(self.first_result)
        self.horizontalLayout.addWidget(self.spinBox)
        self.lineEdit_pen_total_price = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Caveat")
        font.setPointSize(16)
        self.lineEdit_pen_total_price.setFont(font)
        self.lineEdit_pen_total_price.setObjectName("lineEdit_pen_total_price")
        self.horizontalLayout.addWidget(self.lineEdit_pen_total_price)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Caveat")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_rice_price = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Caveat")
        font.setPointSize(16)
        self.lineEdit_rice_price.setFont(font)
        self.lineEdit_rice_price.setObjectName("lineEdit_rice_price")
        self.horizontalLayout_2.addWidget(self.lineEdit_rice_price)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.doubleSpinBox.valueChanged.connect(self.second_result)
        self.horizontalLayout_2.addWidget(self.doubleSpinBox)
        self.lineEdit_rice_total_price = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Caveat")
        font.setPointSize(16)
        self.lineEdit_rice_total_price.setFont(font)
        self.lineEdit_rice_total_price.setObjectName("lineEdit_rice_total_price")
        self.horizontalLayout_2.addWidget(self.lineEdit_rice_total_price)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_result = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Caveat")
        font.setPointSize(22)
        self.label_result.setFont(font)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.verticalLayout.addWidget(self.label_result)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def first_result(self):
        pen_price = int(self.lineEdit_pen_price.text())
        total_pen_price = pen_price * self.spinBox.value()
        self.lineEdit_pen_total_price.setText(str(total_pen_price))

    def second_result(self):
        rice_price = int(self.lineEdit_rice_price.text())
        total_rice_price = rice_price * self.doubleSpinBox.value()
        self.lineEdit_rice_total_price.setText(str(total_rice_price))
        total_price_all = int(self.lineEdit_pen_total_price.text()) + total_rice_price

        self.label_result.setText(f"Total price is : {total_price_all}")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "QSpinBoxes_Example"))
        self.label.setText(_translate("Form", "pen price :"))
        self.label_2.setText(_translate("Form", "rice price :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
