# Form implementation generated from reading ui file '.\QListWidgetAddItemUi.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QWidget

class Ui_Form(QWidget):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 500)
        Form.setWindowIcon(QtGui.QIcon("logo.png"))
        Form.setStyleSheet("QWidget\n"
"{\n"
"background-color :rgb(255, 0, 255)\n"
"}\n"
"QListWidget\n"
"{\n"
"background-color: rgb(255, 170, 255);\n"
"border-radius : 10;\n"
"}\n"
"QLineEdit\n"
"{\n"
"background-color: rgb(255, 211, 253);\n"
"border-radius: 10;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Caveat")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Caveat")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.returnPressed.connect(self.lineEdit_add_Item)
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.listWidget = QtWidgets.QListWidget(Form)
        font = QtGui.QFont()
        font.setFamily("Caveat")
        font.setPointSize(12)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.listWidget.clicked.connect(self.listWidget_selected)
        self.verticalLayout.addWidget(self.listWidget)
        self.label_result = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Caveat")
        font.setPointSize(16)
        self.label_result.setFont(font)
        self.label_result.setObjectName("label_result")
        self.verticalLayout.addWidget(self.label_result)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def lineEdit_add_Item(self):
        item = self.lineEdit.text()
        self.lineEdit.clear()
        self.listWidget.addItem(item)

    def listWidget_selected(self):
        item = self.listWidget.currentItem()
        self.label_result.setText(f"your favorite langauge is {item.text()}")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "QListWidgetAddItemDemo"))
        self.label.setText(_translate("Form", "Enter your favorite Language :"))
        self.label_result.setText(_translate("Form", "waitting ..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
