# Form implementation generated from reading ui file '.\CrudWithQListWidgetDemo.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QDialog, QInputDialog, QLineEdit, QMessageBox
from time import sleep


class Ui_Dialog(QDialog):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(674, 500)
        Dialog.setStyleSheet("QDialog\n"
"{\n"
"background-color : rgb(255, 0, 255);\n"
"border-radius: 25;\n"
"}\n"
"QPushButton {\n"
"background-color : rgb(255, 158, 254);\n"
"border-radius: 5;\n"
"}\n"
"QListWidget\n"
"{\n"
"background-color : rgb(254, 205, 255);\n"
"border-radius: 20;\n"
"}\n"
"\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_add = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setObjectName("pushButton_add")
        self.verticalLayout.addWidget(self.pushButton_add)

        # connect add button signal
        self.pushButton_add.clicked.connect(self.add_Item)

        self.pushButton_Edit = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_Edit.setFont(font)
        self.pushButton_Edit.setObjectName("pushButton_Edit")
        self.verticalLayout.addWidget(self.pushButton_Edit)

        # connect edit button to signal
        self.pushButton_Edit.clicked.connect(self.edit_Item)

        self.pushButton_remove = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_remove.setFont(font)
        self.pushButton_remove.setObjectName("pushButton_remove")
        self.verticalLayout.addWidget(self.pushButton_remove)

        # connect remove button to signal
        self.pushButton_remove.clicked.connect(self.remove_Item)

        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_Sort = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_Sort.setFont(font)
        self.pushButton_Sort.setObjectName("pushButton_Sort")

        # connect remove button to signal
        self.pushButton_Sort.clicked.connect(self.sort_Item)

        self.verticalLayout.addWidget(self.pushButton_Sort)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def add_Item(self):
        row = self.listWidget.currentRow()
        Title = "Add Item Window"
        Message = "Enter Your object name :"
        data, Ok = QInputDialog.getText(self, Title, Message)
        if Ok and data is not None:
            self.listWidget.insertItem(row, data)
        self.label.setText("Item added")



    def edit_Item(self):
        row = self.listWidget.currentRow()
        item = self.listWidget.item(row)
        if item is not None:
            Title = "Edit"
            Message = "Edit your Item :"
            data, ok = QInputDialog.getText(self, Title, Message, QLineEdit.EchoMode.Normal, item.text())
            if data and ok is not None:
                item.setText(data)
        self.label.setText("Item Edited")

    def remove_Item(self):
        row = self.listWidget.currentRow()
        item = self.listWidget.item(row)

        if item is None:
            return
        reply = QMessageBox.question(self, "Delete", "Do you really want to delete item ?",
                            QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.Cancel)
        if reply == QMessageBox.StandardButton.Yes:
            self.listWidget.takeItem(row)
        self.label.setText("Item Deleted")

    def sort_Item(self):
        self.listWidget.sortItems()
        self.label.setText("Items Sorted")

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Crud With QListWidget in QDialog"))
        self.label.setText(_translate("Dialog", "Waiting ..."))
        self.pushButton_add.setText(_translate("Dialog", "Add"))
        self.pushButton_Edit.setText(_translate("Dialog", "Edit"))
        self.pushButton_remove.setText(_translate("Dialog", "Remove"))
        self.pushButton_Sort.setText(_translate("Dialog", "Sort"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
