# Form implementation generated from reading ui file '.\connect_and_insert_demo.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector as mc


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(625, 460)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit_database = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_database.setFont(font)
        self.lineEdit_database.setObjectName("lineEdit_database")
        self.horizontalLayout.addWidget(self.lineEdit_database)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton_connect_db = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_connect_db.setFont(font)
        self.pushButton_connect_db.setObjectName("pushButton_connect_db")
        self.verticalLayout.addWidget(self.pushButton_connect_db)

        # connect signal
        self.pushButton_connect_db.clicked.connect(self.connect_db)

        self.label_result_connect = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_result_connect.setFont(font)
        self.label_result_connect.setText("")
        self.label_result_connect.setObjectName("label_result_connect")
        self.verticalLayout.addWidget(self.label_result_connect)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit_username = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_username.setFont(font)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.horizontalLayout_2.addWidget(self.lineEdit_username)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_password = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.horizontalLayout_3.addWidget(self.lineEdit_password)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.pushButton_insert = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_insert.setFont(font)
        self.pushButton_insert.setObjectName("pushButton_connect_db_2")

        # connect signal
        self.pushButton_insert.clicked.connect(self.insert_item)

        self.verticalLayout.addWidget(self.pushButton_insert)
        self.label_result_insert = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_result_insert.setFont(font)
        self.label_result_insert.setText("")
        self.label_result_insert.setObjectName("label_result_insert")
        self.verticalLayout.addWidget(self.label_result_insert)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    def insert_item(self):
        try:
            dbname = self.lineEdit_database.text()
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database=dbname
            )
            mycursor = mydb.cursor()
            username = self.lineEdit_username.text()
            password = self.lineEdit_password.text()

            query = "INSERT INTO users (username, password) VALUES (%s, %s)"
            value = (username, password)
            mycursor.execute(query, value)

            mydb.commit()
            self.label_result_insert.setText("Data Inserted.")
        except mc.Error as e:
            self.label_result_insert.setText("Data Instert failed")
    def connect_db(self):
        try:
            dbname = self.lineEdit_database.text()
            my_db = mc.connect(
                host="localhost",
                user="root",
                password="",
                database=dbname
            )
            self.label_result_connect.setText(f"There is connect with {dbname}")
        except mc.Error as e:
            self.label_result_connect.setText("connect is failed!")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "DataBase Name : "))
        self.pushButton_connect_db.setText(_translate("Form", "Connect DataBase"))
        self.label.setText(_translate("Form", "UserName :"))
        self.label_2.setText(_translate("Form", "PassWord : "))
        self.pushButton_insert.setText(_translate("Form", "Insert Item"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
